### ISSUE TITLE
No HDMI output

### ISSUE THREAD

**Issue by marcofarolfi** [giusedm/Xiaomi_Air_12.5_EFI_O.C#2]
Everything good except no HDMI output
How to fix?

**Comment by giusedm** [comment]
you can prove with new release, because the HDMI work fine in my laptop

**Comment by marcofarolfi** [comment]
Thanks now it works fine with 1080p monitor 👍 I have a 4K monitor also and i see stretched image because Big Sur consider it a square monitor

**Comment by giusedm** [comment]
Ho avuto lo stesso problema con il mio monitor esterno 4k ho risolto comprando un cavo HDMI per il 4k, guarda se funziona

**Comment by marcofarolfi** [comment]
Hai ragione cambiando cavo effettivamente funziona, strano con windows in 4K a 30 fps non avevo problemi. Quando funzionerà l'aux aggiorna la release 😃

**Comment by giusedm** [comment]
Certamente adesso chiudo l'issue

**Comment by giusedm** [comment]
ah noterai anche una maggiore stabilità nel wifi e nel bluetooth
